apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KihaRaito/sofupo-backend
    targetRevision: master
    path: kubernetes/kustomize/overlays/develop
  destination:
    server: https://kubernetes.default.svc
    namespace: sofupo
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
